### ISSUE TITLE
Les tests ne couvrent pas le code

### ISSUE THREAD

**Issue by paul-rezzonico** [cOpeRency/HurtigLastbil#10]

**Comment by TheoMestries** [comment]
- J'ai ajouté un le fichier TestListeDesTypesDeTexto permettant de tester le modèle ListeDesTypesDeTexto.

- J'ai ajouté un le fichier TestPersonne permettant de tester le modèle Personne.

- J'ai ajouté un le fichier TestTypeTexto permettant de tester le modèle TypeTexto.
