### ISSUE TITLE
Methode 'ExempleConfiguration.onCreate(LoC = 98 lines)' | Trop de lignes dans cette fonction

### ISSUE THREAD

**Issue by Taukix** [cOpeRency/HurtigLastbil#18]

**Comment by cOpeRency** [comment]
C'est un fichier qui a été utilisé à un moment donné pour tester manuellement certaines fonctionnalités, c'est rempli de logs, il vaut mieux tester dans des tests automatisés dédiés. Nous l'avons donc supprimé.
