### ISSUE TITLE
Noms des tests ambigus

### ISSUE THREAD

**Issue by Nyotora** [cOpeRency/HurtigLastbil#2]
Le nom de certains tests est ambigu.
Exemple :

> 

    @Test
    fun personne_est_dans_la_liste_blanche() {
        val personne = Personne("John Doe", "CEO", "0123456789")
        val whiteList = ListeBlanche()
        whiteList.listeBlanche.add(personne)
        assertThat(whiteList.estDansLaListeBlanche(personne)).isTrue()
    }

**Comment by Taukix** [comment]
### Changement du noms de plusieurs tests :
   - `test_serialisation_texto()` -> `retourne_un_texto_serialise()`
   - `test_est_rdv_livraison()` -> `texto_est_un_rendez_vous_de_livraison()`
   - `test_est_rdv_remorque_vide()` -> `texto_est_un_rendez_vous_avec_remorque_vide()`
   - `personne_est_dans_la_liste_blanche()` -> `personne_ajoute_dans_la_liste_blanche_est_present_dans_la_liste_blanche()`
   - `personne_nest_pas_dans_la_liste_blanche()` -> `personne_pas_ajoute_nest_pas_present_dans_la_liste_blanche()`
