### ISSUE TITLE
l'utilisateur peut modifier les messages dans le dossiers 

### ISSUE THREAD

**Issue by paul-rezzonico** [cOpeRency/HurtigLastbil#9]

**Comment by cOpeRency** [comment]
Finalement, nous pouvons seulement ouvrir les fichiers du téléphone en lecture seule, nous ne pouvons donc pas les réécrire (ce qui aurait été problématique, car un camionneur aurait pu trafiquer les messages qu'il a reçu) :

![LectureSeuleLogs](https://github.com/cOpeRency/HurtigLastbil/assets/122995158/9982c9c1-9a6a-438a-a0af-47318b486818)
